# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-22 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=20)),
                ('passport_file', models.FileField(upload_to=b'')),
                ('role', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], default='guest', max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
